
name: dsap

channels:
  - conda-forge

dependencies:
  - python=3.9
  - jupyter
  - jupyter_contrib_nbextensions
  - jupyterlab
  - ipython
  - ipywidgets
  - matplotlib
  - numpy
  - pandas
  - seaborn
  - sympy
  - scipy
  - scikit-image
  - networkx
  - pip
  - pip:
    - ddeint            # Scipy-based delay differential equation (DDE) solver (see also http://pydelay.sourceforge.net)
    - PythonTurtle     # https://github.com/PythonTurtle/PythonTurtle
    
    


# Install a DSAP kernel
# python -m ipykernel install --user --name dsap --display-name "DSAP"

# To remove and reinstall the dsap environment (if installation problems):
# conda deactivate
# conda env remove -n dsap
# conda env dsap
